"use strict";(()=>{var e={};e.id=1034,e.ids=[1034],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},14300:e=>{e.exports=require("buffer")},6113:e=>{e.exports=require("crypto")},82361:e=>{e.exports=require("events")},13685:e=>{e.exports=require("http")},95687:e=>{e.exports=require("https")},41808:e=>{e.exports=require("net")},85477:e=>{e.exports=require("punycode")},12781:e=>{e.exports=require("stream")},24404:e=>{e.exports=require("tls")},57310:e=>{e.exports=require("url")},59796:e=>{e.exports=require("zlib")},14231:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>k,patchFetch:()=>S,requestAsyncStorage:()=>g,routeModule:()=>d,serverHooks:()=>y,staticGenerationAsyncStorage:()=>h});var i={};r.r(i),r.d(i,{GET:()=>m,dynamic:()=>l});var n=r(49303),o=r(88716),a=r(60670),s=r(87070),c=r(85662),u=r(81829);let l="force-dynamic";async function m(e){try{let{searchParams:t}=new URL(e.url),r=t.get("range")||"today",i=(0,u.eG)(),n=new Date(i);switch(r){case"today":default:n.setHours(0,0,0,0);break;case"week":n.setDate(i.getDate()-7);break;case"month":n.setMonth(i.getMonth()-1)}let{data:o,error:a}=await c.p.from("sessions").select(`
        id,
        checkin_ts,
        checkout_ts,
        mode,
        employees (
          id,
          full_name,
          slug
        )
      `).gte("checkin_ts",n.toISOString()).lte("checkin_ts",i.toISOString()).order("checkin_ts",{ascending:!1}).limit(20);if(a)return console.error("Error fetching recent activity:",a),s.NextResponse.json({error:a.message},{status:500});let l=o?.map(e=>{let t=Array.isArray(e.employees)?e.employees[0]:e.employees,r=new Date(e.checkin_ts);return{id:e.id,employeeName:t?.full_name||"Unknown",employeeSlug:t?.slug||"",checkinTime:r.toISOString(),checkinTimeIST:r.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}),date:r.toISOString().split("T")[0],mode:e.mode,isOpen:!e.checkout_ts,timeAgo:p(r,i)}})||[],{data:m}=await c.p.from("sessions").select(`
        id,
        checkin_ts,
        mode,
        employees (
          id,
          full_name,
          slug
        )
      `).is("checkout_ts",null).order("checkin_ts",{ascending:!1}),d=m?.map(e=>{let t=Array.isArray(e.employees)?e.employees[0]:e.employees,r=new Date(e.checkin_ts);return{employeeName:t?.full_name||"Unknown",employeeSlug:t?.slug||"",checkinTime:r.toISOString(),checkinTimeIST:r.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}),mode:e.mode,timeAgo:p(r,i)}})||[];return s.NextResponse.json({recentActivity:l,currentlyCheckedIn:d,range:r,startDate:n.toISOString(),endDate:i.toISOString(),totalRecentSessions:l.length,totalCurrentlyCheckedIn:d.length})}catch(e){return console.error("Recent activity error:",e),s.NextResponse.json({error:e instanceof Error?e.message:"Unknown error"},{status:500})}}function p(e,t){let r=Math.floor((t.getTime()-e.getTime())/6e4),i=Math.floor(r/60),n=Math.floor(i/24);return n>0?`${n} day${n>1?"s":""} ago`:i>0?`${i} hour${i>1?"s":""} ago`:r>0?`${r} minute${r>1?"s":""} ago`:"Just now"}let d=new n.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/admin/recent-activity/route",pathname:"/api/admin/recent-activity",filename:"route",bundlePath:"app/api/admin/recent-activity/route"},resolvedPagePath:"/Users/rishiraj/Downloads/checkin-main/app/api/admin/recent-activity/route.ts",nextConfigOutput:"",userland:i}),{requestAsyncStorage:g,staticGenerationAsyncStorage:h,serverHooks:y}=d,k="/api/admin/recent-activity/route";function S(){return(0,a.patchFetch)({serverHooks:y,staticGenerationAsyncStorage:h})}},85662:(e,t,r)=>{r.d(t,{p:()=>a});var i=r(12814);let n="https://mfbgnipqkkkredgmediu.supabase.co",o=process.env.SUPABASE_SERVICE_ROLE_KEY||"placeholder-service-role";(0,i.eI)(n,"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYmduaXBxamtrcmVkZ21lZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQxNzI5OTksImV4cCI6MjAzOTc0ODk5OX0.1wz9tDfhObRgN0gw0TcvJQ0ZhM0QGsp-R5z70BFZB7M");let a=(0,i.eI)(n,o,{auth:{persistSession:!1,autoRefreshToken:!1}})},81829:(e,t,r)=>{r.d(t,{It:()=>s,JE:()=>a,eG:()=>n,rb:()=>o});let i="Asia/Kolkata",n=()=>new Date,o=()=>{let e=n().getDay();return e>=1&&e<=5},a=e=>{try{return new Date(e).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:i})}catch{return new Date(e).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}},s=e=>{try{return new Date(e).toLocaleDateString("en-CA",{timeZone:i})}catch{return new Date(e).toLocaleDateString("en-CA")}}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),i=t.X(0,[8948,5972,2814],()=>r(14231));module.exports=i})();