"use strict";(()=>{var e={};e.id=2204,e.ids=[2204],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},14300:e=>{e.exports=require("buffer")},6113:e=>{e.exports=require("crypto")},82361:e=>{e.exports=require("events")},13685:e=>{e.exports=require("http")},95687:e=>{e.exports=require("https")},41808:e=>{e.exports=require("net")},85477:e=>{e.exports=require("punycode")},12781:e=>{e.exports=require("stream")},24404:e=>{e.exports=require("tls")},57310:e=>{e.exports=require("url")},59796:e=>{e.exports=require("zlib")},9611:(e,r,t)=>{t.r(r),t.d(r,{originalPathname:()=>h,patchFetch:()=>v,requestAsyncStorage:()=>d,routeModule:()=>p,serverHooks:()=>g,staticGenerationAsyncStorage:()=>m});var a={};t.r(a),t.d(a,{GET:()=>c,dynamic:()=>u});var s=t(49303),o=t(88716),n=t(60670),i=t(87070),l=t(89590);async function c(e){try{let r=new URL(e.url),t=r.searchParams.get("slug")||"",a=r.searchParams.get("email")||"",s=parseInt(r.searchParams.get("year")||new Date().getFullYear().toString());if(!t&&!a)return i.NextResponse.json({error:"slug or email required"},{status:400});let o=await (0,l.H)(t||a,s);if(o.error)return i.NextResponse.json({error:o.error},{status:404});return i.NextResponse.json(o)}catch(e){return console.error("Error in leave balance API:",e),i.NextResponse.json({error:e instanceof Error?e.message:"Unknown error"},{status:500})}}let u="force-dynamic",p=new s.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/leave/balance/route",pathname:"/api/leave/balance",filename:"route",bundlePath:"app/api/leave/balance/route"},resolvedPagePath:"/Users/rishiraj/Downloads/checkin-main/app/api/leave/balance/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:d,staticGenerationAsyncStorage:m,serverHooks:g}=p,h="/api/leave/balance/route";function v(){return(0,n.patchFetch)({serverHooks:g,staticGenerationAsyncStorage:m})}},89590:(e,r,t)=>{t.d(r,{H:()=>s});var a=t(85662);async function s(e,r=new Date().getFullYear()){try{let{data:t}=await a.p.from("employees").select("id, full_name, slug").eq("slug",e).maybeSingle();if(!t)return{error:"employee not found"};let{data:s,error:o}=await a.p.rpc("get_employee_leave_balance",{emp_id:t.id,target_year:r});if(o)return console.error("Error fetching leave balance:",o),{error:o.message};let{data:n,error:i}=await a.p.from("leave_accruals").select(`
        month,
        extra_office_days,
        accrued_leaves,
        calculation_date
      `).eq("employee_id",t.id).eq("year",r).order("month",{ascending:!0});i&&console.error("Error fetching accrual history:",i);let{data:l,error:c}=await a.p.from("leave_requests").select(`
        id,
        start_date,
        end_date,
        total_days,
        reason,
        status,
        created_at,
        leave_types(name)
      `).eq("employee_id",t.id).in("status",["pending","approved"]).gte("start_date",`${r}-01-01`).lte("start_date",`${r}-12-31`).order("created_at",{ascending:!1});return c&&console.error("Error fetching pending requests:",c),{employee:t,year:r,leaveBalance:s||[],accrualHistory:n||[],pendingRequests:l||[]}}catch(e){return console.error("Error in getEmployeeLeaveBalance:",e),{error:e instanceof Error?e.message:"Unknown error"}}}},85662:(e,r,t)=>{t.d(r,{p:()=>n});var a=t(12814);let s="https://mfbgnipqkkkredgmediu.supabase.co",o=process.env.SUPABASE_SERVICE_ROLE_KEY||"placeholder-service-role";(0,a.eI)(s,"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYmduaXBxamtrcmVkZ21lZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQxNzI5OTksImV4cCI6MjAzOTc0ODk5OX0.1wz9tDfhObRgN0gw0TcvJQ0ZhM0QGsp-R5z70BFZB7M");let n=(0,a.eI)(s,o,{auth:{persistSession:!1,autoRefreshToken:!1}})}};var r=require("../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),a=r.X(0,[8948,5972,2814],()=>t(9611));module.exports=a})();