"use strict";(()=>{var e={};e.id=3071,e.ids=[3071],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},14300:e=>{e.exports=require("buffer")},6113:e=>{e.exports=require("crypto")},82361:e=>{e.exports=require("events")},13685:e=>{e.exports=require("http")},95687:e=>{e.exports=require("https")},41808:e=>{e.exports=require("net")},85477:e=>{e.exports=require("punycode")},12781:e=>{e.exports=require("stream")},24404:e=>{e.exports=require("tls")},57310:e=>{e.exports=require("url")},59796:e=>{e.exports=require("zlib")},32163:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>k,patchFetch:()=>S,requestAsyncStorage:()=>p,routeModule:()=>l,serverHooks:()=>h,staticGenerationAsyncStorage:()=>g});var o={};r.r(o),r.d(o,{GET:()=>c,dynamic:()=>d});var i=r(49303),n=r(88716),a=r(60670),s=r(87070),u=r(85662),m=r(81829);let d="force-dynamic";async function c(e){try{let t;let{searchParams:r}=new URL(e.url),o=r.get("range")||"week",i=(0,m.eG)(),n=new Date(i);switch(o){case"week":default:(t=new Date(i)).setDate(i.getDate()-7);break;case"month":(t=new Date(i)).setMonth(i.getMonth()-1)}let{data:a,error:d}=await u.p.from("sessions").select(`
        id,
        checkin_ts,
        checkout_ts,
        mood,
        mood_comment,
        mode,
        employees (
          id,
          full_name,
          slug
        )
      `).gte("checkin_ts",t.toISOString()).lte("checkin_ts",n.toISOString()).not("mood","is",null).order("checkin_ts",{ascending:!0});if(d)return s.NextResponse.json({error:d.message},{status:500});let c=a?.map(e=>{let t=new Date(e.checkin_ts),r=e.checkout_ts?new Date(e.checkout_ts):null,o="N/A";if(r){let e=r.getTime()-t.getTime();o=`${Math.floor(e/(1e3*60*60))}h ${Math.floor(e%(1e3*60*60)/(1e3*60))}m`}let i=Array.isArray(e.employees)?e.employees[0]:e.employees,n=i?.full_name||"Unknown",a=i?.slug||"";return{id:e.id,name:n,slug:a,date:t.toISOString().split("T")[0],checkinTime:t.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}),checkoutTime:r?r.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}):"N/A",workedHours:o,mood:e.mood,moodComment:e.mood_comment||"",mode:e.mode,dayOfWeek:t.toLocaleDateString("en-US",{weekday:"long"})}})||[];return s.NextResponse.json({moodData:c,timeRange:o,startDate:t.toISOString(),endDate:n.toISOString(),totalMoodEntries:c.length})}catch(e){return s.NextResponse.json({error:e instanceof Error?e.message:"Unknown error"},{status:500})}}let l=new i.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/admin/mood-data/route",pathname:"/api/admin/mood-data",filename:"route",bundlePath:"app/api/admin/mood-data/route"},resolvedPagePath:"/Users/rishiraj/Downloads/checkin-main/app/api/admin/mood-data/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:p,staticGenerationAsyncStorage:g,serverHooks:h}=l,k="/api/admin/mood-data/route";function S(){return(0,a.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:g})}},85662:(e,t,r)=>{r.d(t,{p:()=>a});var o=r(12814);let i="https://mfbgnipqkkkredgmediu.supabase.co",n=process.env.SUPABASE_SERVICE_ROLE_KEY||"placeholder-service-role";(0,o.eI)(i,"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYmduaXBxamtrcmVkZ21lZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQxNzI5OTksImV4cCI6MjAzOTc0ODk5OX0.1wz9tDfhObRgN0gw0TcvJQ0ZhM0QGsp-R5z70BFZB7M");let a=(0,o.eI)(i,n,{auth:{persistSession:!1,autoRefreshToken:!1}})},81829:(e,t,r)=>{r.d(t,{It:()=>s,JE:()=>a,eG:()=>i,rb:()=>n});let o="Asia/Kolkata",i=()=>new Date,n=()=>{let e=i().getDay();return e>=1&&e<=5},a=e=>{try{return new Date(e).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:o})}catch{return new Date(e).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}},s=e=>{try{return new Date(e).toLocaleDateString("en-CA",{timeZone:o})}catch{return new Date(e).toLocaleDateString("en-CA")}}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[8948,5972,2814],()=>r(32163));module.exports=o})();