"use strict";(()=>{var e={};e.id=3578,e.ids=[3578],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},14300:e=>{e.exports=require("buffer")},6113:e=>{e.exports=require("crypto")},82361:e=>{e.exports=require("events")},13685:e=>{e.exports=require("http")},95687:e=>{e.exports=require("https")},41808:e=>{e.exports=require("net")},85477:e=>{e.exports=require("punycode")},12781:e=>{e.exports=require("stream")},24404:e=>{e.exports=require("tls")},57310:e=>{e.exports=require("url")},59796:e=>{e.exports=require("zlib")},27368:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>S,patchFetch:()=>I,requestAsyncStorage:()=>p,routeModule:()=>d,serverHooks:()=>h,staticGenerationAsyncStorage:()=>g});var o={};r.r(o),r.d(o,{GET:()=>m,dynamic:()=>c});var n=r(49303),a=r(88716),i=r(60670),s=r(87070),l=r(85662),u=r(81829);let c="force-dynamic";async function m(e){try{let t;console.log("=== HISTORICAL DATA DEBUG ===");let{searchParams:r}=new URL(e.url),o=r.get("range")||"week",n=r.get("startDate"),a=r.get("endDate");console.log("Time range requested:",o),console.log("Custom dates:",n,a);let i=(0,u.eG)();console.log("Current IST time:",i.toISOString()),console.log("Current IST time (local):",i.toString());let c=new Date(i);if(n&&a)t=new Date(n),(c=new Date(a)).setHours(23,59,59,999);else switch(o){case"week":default:(t=new Date(i)).setDate(i.getDate()-7);break;case"month":(t=new Date(i)).setMonth(i.getMonth()-1);break;case"currentMonth":t=new Date(i.getFullYear(),i.getMonth(),1),c=new Date(i.getFullYear(),i.getMonth()+1,0,23,59,59,999);break;case"previousMonth":t=new Date(i.getFullYear(),i.getMonth()-1,1),c=new Date(i.getFullYear(),i.getMonth(),0,23,59,59,999)}console.log("Date range:",t.toISOString(),"to",c.toISOString());let{data:m,error:d}=await l.p.from("sessions").select(`
        id,
        employee_id,
        checkin_ts,
        checkout_ts,
        mode,
        mood,
        mood_comment,
        employees (
          id,
          full_name,
          slug
        )
      `).gte("checkin_ts",t.toISOString()).lte("checkin_ts",c.toISOString()).order("checkin_ts",{ascending:!0});if(d)return console.log("Supabase error:",d),s.NextResponse.json({error:d.message},{status:500});console.log("Sessions found:",m?.length||0);let p=m?.map(e=>{let t=new Date(e.checkin_ts),r=e.checkout_ts?new Date(e.checkout_ts):null,o="N/A";if(r){let e=r.getTime()-t.getTime();o=`${Math.floor(e/(1e3*60*60))}h ${Math.floor(e%(1e3*60*60)/(1e3*60))}m`}let n=Array.isArray(e.employees)?e.employees[0]:e.employees,a=n?.full_name||"Unknown",i=n?.slug||"";return{id:e.id,employee_id:e.employee_id,name:a,slug:i,date:t.toISOString().split("T")[0],firstIn:t.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}),lastOut:r?r.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}):"N/A",totalHours:o,mode:e.mode,status:r?"Complete":"Active",open:!r,mood:e.mood,mood_comment:e.mood_comment}})||[];return s.NextResponse.json({attendanceData:p,timeRange:o,startDate:t.toISOString(),endDate:c.toISOString(),totalSessions:p.length})}catch(e){return s.NextResponse.json({error:e instanceof Error?e.message:"Unknown error"},{status:500})}}let d=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/admin/historical-data/route",pathname:"/api/admin/historical-data",filename:"route",bundlePath:"app/api/admin/historical-data/route"},resolvedPagePath:"/Users/rishiraj/Downloads/checkin-main/app/api/admin/historical-data/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:p,staticGenerationAsyncStorage:g,serverHooks:h}=d,S="/api/admin/historical-data/route";function I(){return(0,i.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:g})}},85662:(e,t,r)=>{r.d(t,{p:()=>i});var o=r(12814);let n="https://mfbgnipqkkkredgmediu.supabase.co",a=process.env.SUPABASE_SERVICE_ROLE_KEY||"placeholder-service-role";(0,o.eI)(n,"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYmduaXBxamtrcmVkZ21lZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQxNzI5OTksImV4cCI6MjAzOTc0ODk5OX0.1wz9tDfhObRgN0gw0TcvJQ0ZhM0QGsp-R5z70BFZB7M");let i=(0,o.eI)(n,a,{auth:{persistSession:!1,autoRefreshToken:!1}})},81829:(e,t,r)=>{r.d(t,{It:()=>s,JE:()=>i,eG:()=>n,rb:()=>a});let o="Asia/Kolkata",n=()=>new Date,a=()=>{let e=n().getDay();return e>=1&&e<=5},i=e=>{try{return new Date(e).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:o})}catch{return new Date(e).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}},s=e=>{try{return new Date(e).toLocaleDateString("en-CA",{timeZone:o})}catch{return new Date(e).toLocaleDateString("en-CA")}}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[8948,5972,2814],()=>r(27368));module.exports=o})();